version: ~> 1.0
import: scala/scala-dev:travis/default.yml

language: scala

git:
  depth: false # Avoid sbt-dynver not seeing the tag

scala:
  - 2.13.6

env:
  - ADOPTOPENJDK=8
  - ADOPTOPENJDK=11

script:
  - sbt ++$TRAVIS_SCALA_VERSION 'testOnly -- xonly timefactor 5' publishLocal

jobs:
  include:
    - stage: test
      name: "Validations"
      script: sbt mimaReportBinaryIssues validateCode doc
      scala: 2.13.6
      jdk: openjdk11
    - stage: publish
      name: "Publish artifacts to Sonatype"
      script: sbt +publish

stages:
  - name: test
  - name: publish
    if: (tag IS present) AND NOT fork

branches:
  only:
    - main
    - /^\d+\.\d+(\.\d+)?(-\S*)?$/
